### ISSUE TITLE
ResponseFormatter: именование поля ответа

### ISSUE THREAD

**Issue by kugimiya** [free-coders-nutshell/backend-board#6]
Сейчас в ответе API поле, которое несёт полезную нагрузку (aka данные), имеет название `data`:
`'data' => data response`

Предлагаю переименовать это поле в `payload`.

**Comment by ridouchire** [comment]
А в чём разница? Почему текущий вариант плох?

**Comment by kugimiya** [comment]
@ridouchire, просто так принято, что поле с данными называют `payload`.
https://techterms.com/definition/payload

Да и просто выглядит серьезно, кмк. :^)

**Comment by ridouchire** [comment]
Разумно. 

Взял в работу.

**Comment by ridouchire** [comment]
Переименовал.
